### ISSUE TITLE
[가게 관련] 버그 목록

### ISSUE THREAD

**Issue by seungh0** [3dollar-in-my-pocket/3dollars-in-my-pocket-ios#143]
## 가게 메인 화면
- [x] 사장님 직영점만 필터링 작동 안함
- [x] [리스트 뷰] => 다른 탭 갔다가 => [지도 뷰] 클릭시 화면이 안보임 (#141)
- [x] (버그 x) 초기에 10개만 가게가 보여서.. 넘 적은거 같아서, 좀 더 보여주는건 어떨까요? 

## 가게 상세
- [x] 메뉴가 많아지면, 가게 사진 ui 깨짐
- [x] 가게 상세 화면에서, 이미지 등록시, 최신순이 아니라, 오래된 순으로 순서가 저장됨 (맨 왼쪽에 저장되어야 하는대, 반대로 되는거 같음)
- [x] 공유하기 동작 안함
- [x] 삭제된 가게 접근시 (404 떨어짐) 빈 화면이 노출되고, 에러 메시지 없음
- [x] 방문 인증이 많아지면, UI가 늘어나는현상 (#139)
- [x] 메뉴 더보기 동작 안함

## 가게 등록
- [x] 메뉴 등록시, 2개씩 증가하는 현상이 있음
- [x] (동일 카테고리) 메뉴를 2번째꺼 작성 후, 첫번째 메뉴를 작성한 후, 가게 등록시 메뉴가 총 4개가 등록됨 (#140)

## 가게 수정
- [x] 출몰시기 변경 후, 상세 화면 가면 반영 안되어있음 (일부만 안되는것 같음 - 일요일, 취소시 반영 안되는거 같음) (#138)

## 리뷰 

- [x] 리뷰 목록 중, 내가 작성한 리뷰는 [신고]가 아닌 [수정 or 삭제]가 노출되어야 할 거 같음
- [x] 리뷰 신고 “기타” 클릭시 화면이 올라가서, 신고 내용을 입력할 수 없음 (142와 다른 이슈)
- [x] 리뷰 작성시 평점 1로 하면, 2로 저장됨 (평점이 1씩 높게 저장됨)
- [x] 리뷰 신고 클릭 후 나와서, 다시 신고 클릭시 화면이 안뜸 (#142)

## 즐겨찾기

- [x] 한 1/2 확률로, 즐겨찾기 클릭 안되는 가게들이 있음

## 방문 인증
- [x] (버그 x) 방문 성공 후, 메시지 하나 남기는 것도 좋을거 같습니다!

## 현상이 발생하는 앱 버전과 디바이스를 적어주세요. 📱
- 앱 버전: v4.0.0(55)
- 디바이스: iphone 13 mini

**Comment by Hyunsik-Yoo** [comment]
> (버그 x) 초기에 10개만 가게가 보여서.. 넘 적은거 같아서, 좀 더 보여주는건 어떨까요?

이 내용도 버그였어서 59 이상 버전에서 수정되었어요!!
초기 조회시에 좁은 범위로 검색하고 있었습니다..!

**Comment by Hyunsik-Yoo** [comment]
> 메뉴가 많아지면, 가게 사진 ui 깨짐
- 이건 메뉴가 아니라 인증이겠죠?? 만약 메뉴도 동일하다면 발생하는 가게 알려주세요!

> 가게 상세 화면에서, 이미지 등록시, 최신순이 아니라, 오래된 순으로 순서가 저장됨 (맨 왼쪽에 저장되어야 하는대, 반대로 되는거 같음)
- 이 내용도 가장 마지막에 등록한 사진이 가장 왼쪽에 뜨고 있는데 아니라면 알려주세요!

**Comment by seungh0** [comment]
> (버그 x) 초기에 10개만 가게가 보여서.. 넘 적은거 같아서, 좀 더 보여주는건 어떨까요?
> 
> 이 내용도 버그였어서 59 이상 버전에서 수정되었어요!!
> 초기 조회시에 좁은 범위로 검색하고 있었습니다..!


- 아하 버그가 있었군요.. 추가로 주변 가게를 최대 10개 조회하고 있는데요, 가게가 많은 지역쪽을 고려했을때, 좀 더 한번에 조회하는 가게 갯수를 늘리는건 어떨까 싶네요

**Comment by Hyunsik-Yoo** [comment]
@seungh0 서버에서 내려주는 개수를 최대 10개보다 더 늘린다는거죠??

**Comment by seungh0** [comment]
@Hyunsik-Yoo  엇 늘릴려면 클라이언트에서 파라미터로 늘려야할거 같습니다.
지금도 괜찮은거 같기도하고.. 애매하네요

**Comment by seungh0** [comment]
@Hyunsik-Yoo 리스트 뷰 처럼 지도 뷰도, 메인 카드들 10개 다 보면, 다음 카드들 더 나오게하는건 어려울까요?

**Comment by Hyunsik-Yoo** [comment]
> @Hyunsik-Yoo 리스트 뷰 처럼 지도 뷰도, 메인 카드들 10개 다 보면, 다음 카드들 더 나오게하는건 어려울까요?
> 이슈가 있다면 지금처럼 가도 좋을거 같습니다!

요거는 한번 고민해볼께요!
- 마커를 점점 늘리는 식으로 해도 될 것 같기도 하네요!
